topics:
- name    : pad
  topic   : pad_teleop/cmd_vel
  timeout : 0.5
  priority: 200

- name    : move_base
  topic   : move_base/cmd_vel
  timeout : 0.5
  priority: 50

- name    : mpc
  topic   : controller/cmd_vel
  timeout : 0.5
  priority: 50

- name    : external
  topic   : cmd_vel
  timeout : 0.5
  priority: 20

locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0
  priority: 255
