global_frame: map
robot_base_frame: base_link

obstacle_range: 5.5
raytrace_range: 6.0

# Box robot
# footprint: [[0.85, -0.4], [0.85, 0.4], [-0.15, 0.4], [-0.15, -0.4]]

footprint: [[2.400, -1.0], [2.400, 1], [-0.400, 1.0], [-0.400, -1]]

publish_frequency: 5.0

obstacle_layer:
  enabled: true
  observation_sources: scan2d # scan3d
  scan2d:
    data_type: LaserScan
    topic: front_laser/scan
    marking: true
    clearing: true
    inf_is_valid: true
    min_obstacle_height: 0.1

  scan3d:
    data_type: PointCloud2
    topic: velodyne_points
    marking: true
    clearing: true
    inf_is_valid: false
    min_obstacle_height: 0.3
