local_costmap:
  global_frame: /odom
  robot_base_frame: /base_footprint
  update_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 10.0 #5
  height: 10.0 #5
  resolution: 0.05 #0.05

  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0

  plugins:
    - name: obstacle_layer
      type: "costmap_2d::VoxelLayer"
