controller_frequency: 10.0
controller_patience: 30.0 

conservative_reset_dist: 3.0
recovery_behavior_enabled: true
clearing_rotation_allowed: false
shutdown_costmaps: false
oscillation_timeout: 10.0
oscillation_distance: 0.5