base_local_planner: teb_local_planner/TebLocalPlannerROS

TebLocalPlannerROS:
  odom_topic: odom
  map_frame: map

  # Trajectory
  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: True
  max_global_plan_lookahead_dist: 3.0
  feasibility_check_no_poses: 5
  global_plan_viapoint_sep: -1
  global_plan_prune_distance: 1
  exact_arc_length: False
  feasibility_check_no_poses: 2
  publish_feedback: False

  # Robot
  max_vel_x: 3
  max_vel_x_backwards: 0.2
  max_vel_theta: 0.75
  acc_lim_x: 0.5
  acc_lim_theta: 0.5
  min_turning_radius: 2.7 # actual turning radius is approx 2.68, but it is better to set it higher. higher means more restrictive movement
  wheelbase: 1.8 # only used if publishing an ackermann
  cmd_angle_instead_rotvel: false 
  allow_init_with_backwards_motion: true
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    # type: "line"
    # line_start: [-0.20, 0.0] # for type "line"
    # line_end: [0.63, 0.0] # for type "line"
    type: "polygon"
    vertices: [[2.400, -1.0], [2.400, 1], [-0.400, 1.0], [-0.400, -1]]

  # GoalTolerance
  xy_goal_tolerance: 0.4
  yaw_goal_tolerance: 0.5
  free_goal_vel: False
  complete_global_plan: False

  # Obstacles
  min_obstacle_dist: 0.55 # 0.55
  inflation_dist: 0.3
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30
  costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
  # costmap_converter_plugin: "" # deactivate plugin
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5


  # Optimization
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  weight_max_vel_x: 1000
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 10000
  weight_kinematics_forward_drive: 0.0 # not used when min_turning_radius (not the weight!) is != 0
  weight_kinematics_turning_radius: 1 # to ensure that the minimum turning radius is respected
  weight_optimaltime: 1
  weight_obstacle: 50
  weight_dynamic_obstacle: 10 # not in use yet
  selection_alternative_time_cost: False

  # Homotopy Class Planner
  enable_homotopy_class_planning: True
  enable_multithreading: True
  simple_exploration: True
  max_number_classes: 4
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: True

  # Recovery
  shrink_horizon_backup: True
  shrink_horizon_min_duration: 10
  oscillation_recovery: True
  oscillation_v_eps: 0.1
  oscillation_omega_eps: 0.1
  oscillation_recovery_min_duration: 10
  oscillation_filter_duration: 10
